name: Skymu (BETA)

on:
  workflow_dispatch:
  push:
    branches: [ "**" ]

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '5.0.x'

    - name: 1. Build Yggdrasil
      run: dotnet build Yggdrasil/Yggdrasil.csproj --configuration Release --self-contained false

    - name: 2. Build Plugins
      run: |
        Get-ChildItem -Path "Plugins" -Filter "*.csproj" -Recurse | ForEach-Object {
          dotnet build $_.FullName --configuration Release -p:AppendRuntimeIdentifierToOutputPath=false --self-contained false
        }
    - name: 3. Build Skymu
      run: dotnet build Skymu/Skymu.csproj --configuration Release -p:AppendRuntimeIdentifierToOutputPath=false --self-contained false

    - name: 4. Build NSIS
      run: makensis NSIS/SkymuBetaSetup.nsi

    - name: 5. Export Installer to Artifacts
      uses: actions/upload-artifact@v7
      with:
        path: 'NSIS/Skymu Installer (BETA).exe'
        retention-days: 7
        archive: false
