<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<AssemblyName>smp.chatcompletions</AssemblyName>
		<AssemblyTitle>Chat Completions</AssemblyTitle>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<FileVersion>1.0.0.0</FileVersion>
		<PlatformTarget>AnyCPU</PlatformTarget>
		<OutputPath>..\bin\chatcompletions.smp</OutputPath>
		<LangVersion>7.3</LangVersion>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="System.Text.Json" Version="10.0.9" />
		<PackageReference Include="System.Threading.Channels" Version="5.0.0" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\..\Yggdrasil\Yggdrasil.csproj" />
	</ItemGroup>
	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<DebugType>none</DebugType>
	</PropertyGroup>
</Project>
