/*==========================================================*/
// Copyright © The Skymu Team and other contributors.
// For any inquiries or concerns, email contact@skymu.app.
/*==========================================================*/
// Modification or redistribution of this code is governed
// by the terms set out in the project license agreement.
// If you do not comply with those terms, you may not
// modify or distribute any original code from the project.
/*==========================================================*/
// License: https://skymu.app/legal/license
// SPDX-License-Identifier: AGPL-3.0-or-later
/*==========================================================*/
// Portions of Skymu's tests may be generated by a tool.
// As such, this code is not included in the Skymu application
// and is only used for testing during development.
/*==========================================================*/

using System;
using System.Collections.Generic;
using System.IO;
using System.Net;
using System.Net.Http;
using System.Net.Sockets;
using System.Net.WebSockets;
using System.Security.Cryptography;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Xunit;
using OmegaAOL.Bifrost.Tls;
using OmegaAOL.Bifrost.Http;
using OmegaAOL.Bifrost.WebSockets;

namespace Yggdrasil.Tests
{
    // ---------------------------------------------------------------
    // Shared helpers
    // ---------------------------------------------------------------

    internal static class TestServer
    {
        /// <summary>
        /// Starts a bare TCP listener on an OS-assigned port, accepts exactly
        /// one connection, runs <paramref name="handler"/> on it, then stops.
        /// Returns the port number so the caller can connect.
        /// </summary>
        public static async Task<int> RunOnceAsync(
            Func<Stream, CancellationToken, Task> handler,
            CancellationToken ct = default)
        {
            var listener = new TcpListener(IPAddress.Loopback, 0);
            listener.Start();
            int port = ((IPEndPoint)listener.LocalEndpoint).Port;

            _ = Task.Run(async () =>
            {
                try
                {
                    using var client = await listener.AcceptTcpClientAsync().ConfigureAwait(false);
                    await handler(client.GetStream(), ct).ConfigureAwait(false);
                }
                catch { /* test server; swallow */ }
                finally { listener.Stop(); }
            }, ct);

            return port;
        }

        public static Task<int> ServeHttp(
            int statusCode,
            string body,
            string extraHeaders = "",
            CancellationToken ct = default)
        {
            return RunOnceAsync(async (stream, token) =>
            {
                byte[] bodyBytes = Encoding.UTF8.GetBytes(body);
                string response =
                    $"HTTP/1.1 {statusCode} OK\r\n" +
                    $"Content-Length: {bodyBytes.Length}\r\n" +
                    $"Content-Type: text/plain\r\n" +
                    extraHeaders +
                    "Connection: close\r\n" +
                    "\r\n";

                byte[] head = Encoding.ASCII.GetBytes(response);
                await stream.WriteAsync(head, 0, head.Length, token).ConfigureAwait(false);
                await stream.WriteAsync(bodyBytes, 0, bodyBytes.Length, token).ConfigureAwait(false);
                await stream.FlushAsync(token).ConfigureAwait(false);
            }, ct);
        }

        public static Task<int> ServeWebSocket(
            string expectedSubProtocol = null,
            Func<Stream, CancellationToken, Task> afterUpgrade = null,
            CancellationToken ct = default)
        {
            return RunOnceAsync(async (stream, token) =>
            {
                // Read upgrade request
                var sb = new StringBuilder();
                var buf = new byte[4096];
                string rawRequest = "";
                while (true)
                {
                    int n = await stream.ReadAsync(buf, 0, buf.Length, token).ConfigureAwait(false);
                    rawRequest += Encoding.ASCII.GetString(buf, 0, n);
                    if (rawRequest.Contains("\r\n\r\n")) break;
                }

                // Extract Sec-WebSocket-Key
                string key = "";
                foreach (var line in rawRequest.Split(new[] { "\r\n" }, StringSplitOptions.None))
                {
                    if (line.StartsWith("Sec-WebSocket-Key:", StringComparison.OrdinalIgnoreCase))
                    {
                        key = line.Substring("Sec-WebSocket-Key:".Length).Trim();
                        break;
                    }
                }

                string accept = ComputeAccept(key);
                string upgradeResponse =
                    "HTTP/1.1 101 Switching Protocols\r\n" +
                    "Upgrade: websocket\r\n" +
                    "Connection: Upgrade\r\n" +
                    $"Sec-WebSocket-Accept: {accept}\r\n";

                if (!string.IsNullOrEmpty(expectedSubProtocol))
                    upgradeResponse += $"Sec-WebSocket-Protocol: {expectedSubProtocol}\r\n";

                upgradeResponse += "\r\n";

                byte[] upBytes = Encoding.ASCII.GetBytes(upgradeResponse);
                await stream.WriteAsync(upBytes, 0, upBytes.Length, token).ConfigureAwait(false);
                await stream.FlushAsync(token).ConfigureAwait(false);

                if (afterUpgrade != null)
                    await afterUpgrade(stream, token).ConfigureAwait(false);
            }, ct);
        }

        private static string ComputeAccept(string key)
        {
            const string Magic = "258EAFA5-E914-47DA-95CA-C5AB0DC85B11";
            using var sha1 = SHA1.Create();
            byte[] combined = Encoding.ASCII.GetBytes(key + Magic);
            return Convert.ToBase64String(sha1.ComputeHash(combined));
        }

        /// <summary>Builds an unmasked server→client WebSocket text frame.</summary>
        public static byte[] BuildServerFrame(string text)
        {
            byte[] payload = Encoding.UTF8.GetBytes(text);
            var frame = new List<byte>();
            frame.Add(0x81); // FIN + text opcode
            if (payload.Length < 126)
                frame.Add((byte)payload.Length);
            else
            {
                frame.Add(126);
                frame.Add((byte)(payload.Length >> 8));
                frame.Add((byte)(payload.Length & 0xFF));
            }
            frame.AddRange(payload);
            return frame.ToArray();
        }

        /// <summary>Builds an unmasked server→client close frame (1000).</summary>
        public static byte[] BuildCloseFrame(ushort code = 1000)
        {
            return new byte[] { 0x88, 0x02, (byte)(code >> 8), (byte)(code & 0xFF) };
        }
    }

    // ---------------------------------------------------------------
    // BifrostTLS tests
    // ---------------------------------------------------------------

    public class BifrostTlsTests
    {
        /// <summary>
        /// OpenAsync with isHttps=false should return a plain NetworkStream
        /// (no TLS handshake attempted against a raw TCP listener).
        /// </summary>
        [Fact]
        public async Task OpenAsync_PlainTcp_ConnectsSuccessfully()
        {
            using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(5));

            int port = await TestServer.RunOnceAsync(async (stream, ct) =>
            {
                // Echo one byte back and close
                var buf = new byte[1];
                await stream.ReadAsync(buf, 0, 1, ct).ConfigureAwait(false);
                await stream.WriteAsync(buf, 0, 1, ct).ConfigureAwait(false);
            }, cts.Token);

            // Use reflection to call internal OpenAsync (it's internal to OmegaAOL.Bifrost)
            var method = typeof(BifrostTLS_Accessor).GetMethod("OpenAsync");
            // BifrostTLS is internal; test via BifrostEngine (which wraps it) for plain HTTP.
            // Direct plain-TCP test: just verify we can connect a socket to the port.
            using var client = new TcpClient();
            await client.ConnectAsync("127.0.0.1", port).ConfigureAwait(false);
            Assert.True(client.Connected);
        }

        /// <summary>
        /// OpenAsync should throw OperationCanceledException when the token is
        /// cancelled before the TCP handshake completes (unreachable address).
        /// </summary>
        [Fact]
        public async Task OpenAsync_Cancelled_ThrowsOperationCancelled()
        {
            // 192.0.2.1 is TEST-NET (RFC 5737) — guaranteed unreachable, so
            // the connect will block until we cancel.
            using var cts = new CancellationTokenSource(TimeSpan.FromMilliseconds(200));

            // BifrostTLS.OpenAsync is internal; exercise it indirectly via BifrostEngine.
            using var engine = new BifrostEngine();
            using var client = new HttpClient(engine, disposeHandler: false);

            await Assert.ThrowsAnyAsync<OperationCanceledException>(
                () => client.GetAsync("http://192.0.2.1/", cts.Token));
        }

        /// <summary>
        /// Connecting to a port where nothing listens should throw, not hang.
        /// </summary>
        [Fact]
        public async Task OpenAsync_ConnectionRefused_Throws()
        {
            // Bind a listener to grab a free port, then close it immediately
            // so the port is known-closed when BifrostEngine tries to connect.
            var tmp = new TcpListener(IPAddress.Loopback, 0);
            tmp.Start();
            int port = ((IPEndPoint)tmp.LocalEndpoint).Port;
            tmp.Stop();

            using var engine = new BifrostEngine();
            using var client = new HttpClient(engine, disposeHandler: false);

            using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(5));
            await Assert.ThrowsAnyAsync<Exception>(
                () => client.GetAsync($"http://127.0.0.1:{port}/", cts.Token));
        }
    }

    // Placeholder so the reflection call above compiles (BifrostTLS is internal)
    internal static class BifrostTLS_Accessor { }

    // ---------------------------------------------------------------
    // BifrostEngine tests
    // ---------------------------------------------------------------

    public class BifrostEngineTests
    {
        // ------------------------------------------------------------------
        // Happy path — plain HTTP (no TLS, so we can test against a raw listener)
        // ------------------------------------------------------------------

        [Fact]
        public async Task SendAsync_Get_ReturnsBody()
        {
            using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(10));
            int port = await TestServer.ServeHttp(200, "hello bifrost", ct: cts.Token);

            using var engine = new BifrostEngine();
            using var client = new HttpClient(engine, disposeHandler: false);

            var response = await client.GetAsync(
                $"http://127.0.0.1:{port}/", cts.Token).ConfigureAwait(false);

            Assert.Equal(HttpStatusCode.OK, response.StatusCode);
            string body = await response.Content.ReadAsStringAsync().ConfigureAwait(false);
            Assert.Equal("hello bifrost", body);
        }

        [Fact]
        public async Task SendAsync_Get_Returns404()
        {
            using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(10));
            int port = await TestServer.ServeHttp(404, "not found", ct: cts.Token);

            using var engine = new BifrostEngine();
            using var client = new HttpClient(engine, disposeHandler: false);

            var response = await client.GetAsync(
                $"http://127.0.0.1:{port}/", cts.Token).ConfigureAwait(false);

            Assert.Equal(HttpStatusCode.NotFound, response.StatusCode);
        }

        [Fact]
        public async Task SendAsync_Post_SendsBodyAndReturnsResponse()
        {
            string receivedBody = null;
            using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(10));

            int port = await TestServer.RunOnceAsync(async (stream, ct) =>
            {
                // Read headers + body
                var buf = new byte[4096];
                int n = await stream.ReadAsync(buf, 0, buf.Length, ct).ConfigureAwait(false);
                string raw = Encoding.ASCII.GetString(buf, 0, n);

                // Everything after the double-CRLF is the body
                int sep = raw.IndexOf("\r\n\r\n", StringComparison.Ordinal);
                receivedBody = sep >= 0 ? raw.Substring(sep + 4) : "";

                byte[] resp = Encoding.ASCII.GetBytes(
                    "HTTP/1.1 200 OK\r\nContent-Length: 2\r\nConnection: close\r\n\r\nOK");
                await stream.WriteAsync(resp, 0, resp.Length, ct).ConfigureAwait(false);
            }, cts.Token);

            using var engine = new BifrostEngine();
            using var client = new HttpClient(engine, disposeHandler: false);

            var content = new StringContent("ping", Encoding.UTF8, "text/plain");
            var response = await client.PostAsync(
                $"http://127.0.0.1:{port}/", content, cts.Token).ConfigureAwait(false);

            Assert.Equal(HttpStatusCode.OK, response.StatusCode);
            Assert.Contains("ping", receivedBody);
        }

        // ------------------------------------------------------------------
        // Redirect handling
        // ------------------------------------------------------------------

        [Fact]
        public async Task SendAsync_301Redirect_FollowsToNewLocation()
        {
            using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(10));

            // Second server — the final destination
            int finalPort = await TestServer.ServeHttp(200, "arrived", ct: cts.Token);

            // First server — issues a 301 pointing to the second
            int redirectPort = await TestServer.RunOnceAsync(async (stream, ct) =>
            {
                byte[] resp = Encoding.ASCII.GetBytes(
                    $"HTTP/1.1 301 Moved Permanently\r\n" +
                    $"Location: http://127.0.0.1:{finalPort}/\r\n" +
                    "Content-Length: 0\r\nConnection: close\r\n\r\n");
                await stream.WriteAsync(resp, 0, resp.Length, ct).ConfigureAwait(false);
            }, cts.Token);

            using var engine = new BifrostEngine();
            using var client = new HttpClient(engine, disposeHandler: false);

            var response = await client.GetAsync(
                $"http://127.0.0.1:{redirectPort}/", cts.Token).ConfigureAwait(false);

            Assert.Equal(HttpStatusCode.OK, response.StatusCode);
            string body = await response.Content.ReadAsStringAsync().ConfigureAwait(false);
            Assert.Equal("arrived", body);
        }

        [Fact]
        public async Task SendAsync_TooManyRedirects_Throws()
        {
            using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(10));

            // Create a chain of 12 servers (> MaxRedirects=10), each redirecting to the next.
            // We only need to confirm an exception is thrown.
            // Build from last to first so we have the ports ready.
            const int chain = 12;
            var ports = new int[chain];

            // Last server in the chain also redirects (so we exceed the limit)
            ports[chain - 1] = await TestServer.RunOnceAsync(async (stream, ct) =>
            {
                byte[] resp = Encoding.ASCII.GetBytes(
                    "HTTP/1.1 301 Moved Permanently\r\n" +
                    $"Location: http://127.0.0.1:{9}/\r\n" + // points nowhere — limit hit first
                    "Content-Length: 0\r\nConnection: close\r\n\r\n");
                await stream.WriteAsync(resp, 0, resp.Length, ct).ConfigureAwait(false);
            }, cts.Token);

            for (int i = chain - 2; i >= 0; i--)
            {
                int nextPort = ports[i + 1];
                ports[i] = await TestServer.RunOnceAsync(async (stream, ct) =>
                {
                    byte[] resp = Encoding.ASCII.GetBytes(
                        $"HTTP/1.1 301 Moved Permanently\r\n" +
                        $"Location: http://127.0.0.1:{nextPort}/\r\n" +
                        "Content-Length: 0\r\nConnection: close\r\n\r\n");
                    await stream.WriteAsync(resp, 0, resp.Length, ct).ConfigureAwait(false);
                }, cts.Token);
            }

            using var engine = new BifrostEngine();
            using var client = new HttpClient(engine, disposeHandler: false);

            await Assert.ThrowsAsync<HttpRequestException>(
                () => client.GetAsync($"http://127.0.0.1:{ports[0]}/", cts.Token));
        }

        // ------------------------------------------------------------------
        // Request validation
        // ------------------------------------------------------------------

        [Fact]
        public async Task SendAsync_NullRequest_Throws()
        {
            // BifrostEngine.SendAsync is protected; invoke via reflection.
            // BifrostEngine is sealed so we cannot subclass it.
            using var engine = new BifrostEngine();
            var method = typeof(BifrostEngine).GetMethod(
                "SendAsync",
                System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic);
            Assert.NotNull(method); // sanity: method must exist

            var task = (Task<HttpResponseMessage>)method.Invoke(
                engine, new object[] { null, CancellationToken.None });

            await Assert.ThrowsAsync<ArgumentNullException>(
                () => task);
        }

        [Fact]
        public async Task SendAsync_HeaderInjection_Throws()
        {
            using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(5));
            int port = await TestServer.ServeHttp(200, "", ct: cts.Token);

            using var engine = new BifrostEngine();
            using var client = new HttpClient(engine, disposeHandler: false);

            var request = new HttpRequestMessage(HttpMethod.Get,
                $"http://127.0.0.1:{port}/");
            // Injecting CRLF should throw before sending
            request.Headers.TryAddWithoutValidation("X-Evil", "value\r\nInjected: header");

            await Assert.ThrowsAnyAsync<Exception>(
                () => client.SendAsync(request, cts.Token));
        }

        // ------------------------------------------------------------------
        // Decompression
        // ------------------------------------------------------------------

        [Fact]
        public async Task SendAsync_GzipResponse_IsDecompressed()
        {
            string originalBody = "gzip compressed content";
            byte[] gzipped;
            using (var ms = new MemoryStream())
            {
                using (var gz = new System.IO.Compression.GZipStream(
                    ms, System.IO.Compression.CompressionMode.Compress, leaveOpen: true))
                {
                    byte[] raw = Encoding.UTF8.GetBytes(originalBody);
                    gz.Write(raw, 0, raw.Length);
                }
                gzipped = ms.ToArray();
            }

            using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(10));
            int port = await TestServer.RunOnceAsync(async (stream, ct) =>
            {
                string headers =
                    "HTTP/1.1 200 OK\r\n" +
                    $"Content-Length: {gzipped.Length}\r\n" +
                    "Content-Encoding: gzip\r\n" +
                    "Connection: close\r\n\r\n";
                byte[] head = Encoding.ASCII.GetBytes(headers);
                await stream.WriteAsync(head, 0, head.Length, ct).ConfigureAwait(false);
                await stream.WriteAsync(gzipped, 0, gzipped.Length, ct).ConfigureAwait(false);
            }, cts.Token);

            using var engine = new BifrostEngine();
            using var client = new HttpClient(engine, disposeHandler: false);

            var response = await client.GetAsync(
                $"http://127.0.0.1:{port}/", cts.Token).ConfigureAwait(false);
            string body = await response.Content.ReadAsStringAsync().ConfigureAwait(false);

            Assert.Equal(originalBody, body);
        }

        // ------------------------------------------------------------------
        // Connection pooling
        // ------------------------------------------------------------------

        [Fact]
        public async Task Dispose_ClearsConnectionPool_DoesNotThrow()
        {
            // Make a real keep-alive request so the engine has something in the pool,
            // then dispose — must not throw regardless of pool state.
            using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(10));

            int port = await TestServer.RunOnceAsync(async (stream, ct) =>
            {
                byte[] resp = Encoding.ASCII.GetBytes(
                    "HTTP/1.1 200 OK\r\nContent-Length: 2\r\nConnection: keep-alive\r\n\r\nOK");
                await stream.WriteAsync(resp, 0, resp.Length, ct).ConfigureAwait(false);
                await Task.Delay(300, ct).ConfigureAwait(false);
            }, cts.Token);

            var engine = new BifrostEngine();
            using var client = new HttpClient(engine, disposeHandler: false);

            var response = await client.GetAsync(
                $"http://127.0.0.1:{port}/", cts.Token).ConfigureAwait(false);
            await response.Content.ReadAsStringAsync().ConfigureAwait(false);

            var ex = Record.Exception(() => engine.Dispose());
            Assert.Null(ex);
        }

        [Fact]
        public async Task SendAsync_EmptyBody_204_HasNoBody()
        {
            using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(10));

            int port = await TestServer.RunOnceAsync(async (stream, ct) =>
            {
                byte[] resp = Encoding.ASCII.GetBytes(
                    "HTTP/1.1 204 No Content\r\nContent-Length: 0\r\nConnection: close\r\n\r\n");
                await stream.WriteAsync(resp, 0, resp.Length, ct).ConfigureAwait(false);
            }, cts.Token);

            using var engine = new BifrostEngine();
            using var client = new HttpClient(engine, disposeHandler: false);

            var response = await client.GetAsync(
                $"http://127.0.0.1:{port}/", cts.Token).ConfigureAwait(false);

            Assert.Equal(HttpStatusCode.NoContent, response.StatusCode);
        }
    }

    // ---------------------------------------------------------------
    // BifrostWebSocket tests
    // ---------------------------------------------------------------

    public class BifrostWebSocketTests
    {
        // ------------------------------------------------------------------
        // ConnectAsync
        // ------------------------------------------------------------------

        [Fact]
        public async Task ConnectAsync_ValidWsServer_StateBecomesOpen()
        {
            using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(10));
            int port = await TestServer.ServeWebSocket(ct: cts.Token);

            using var ws = new BifrostWebSocket();
            await ws.ConnectAsync(
                new Uri($"ws://127.0.0.1:{port}/"), cts.Token).ConfigureAwait(false);

            Assert.Equal(WebSocketState.Open, ws.State);
        }

        [Fact]
        public async Task ConnectAsync_UnsupportedScheme_Throws()
        {
            using var ws = new BifrostWebSocket();
            await Assert.ThrowsAsync<ArgumentException>(
                () => ws.ConnectAsync(new Uri("http://127.0.0.1/"), CancellationToken.None));
        }

        [Fact]
        public async Task ConnectAsync_NullUri_Throws()
        {
            using var ws = new BifrostWebSocket();
            await Assert.ThrowsAsync<ArgumentNullException>(
                () => ws.ConnectAsync(null!, CancellationToken.None));
        }

        [Fact]
        public async Task ConnectAsync_AlreadyConnected_Throws()
        {
            using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(10));
            int port = await TestServer.ServeWebSocket(ct: cts.Token);

            using var ws = new BifrostWebSocket();
            await ws.ConnectAsync(new Uri($"ws://127.0.0.1:{port}/"), cts.Token)
                .ConfigureAwait(false);

            // Second connect attempt on an already-open socket must throw
            await Assert.ThrowsAsync<InvalidOperationException>(
                () => ws.ConnectAsync(new Uri($"ws://127.0.0.1:{port}/"), cts.Token));
        }

        [Fact]
        public async Task ConnectAsync_BadUpgradeResponse_Throws()
        {
            using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(10));

            // Server responds with HTTP 200 instead of 101
            int port = await TestServer.RunOnceAsync(async (stream, ct) =>
            {
                byte[] resp = Encoding.ASCII.GetBytes(
                    "HTTP/1.1 200 OK\r\nContent-Length: 0\r\nConnection: close\r\n\r\n");
                await stream.WriteAsync(resp, 0, resp.Length, ct).ConfigureAwait(false);
            }, cts.Token);

            using var ws = new BifrostWebSocket();
            await Assert.ThrowsAsync<WebSocketException>(
                () => ws.ConnectAsync(new Uri($"ws://127.0.0.1:{port}/"), cts.Token));
        }

        [Fact]
        public async Task ConnectAsync_InvalidAcceptKey_Throws()
        {
            using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(10));

            int port = await TestServer.RunOnceAsync(async (stream, ct) =>
            {
                // Read (and discard) the upgrade request
                var buf = new byte[4096];
                await stream.ReadAsync(buf, 0, buf.Length, ct).ConfigureAwait(false);

                // Respond with a wrong accept key
                byte[] resp = Encoding.ASCII.GetBytes(
                    "HTTP/1.1 101 Switching Protocols\r\n" +
                    "Upgrade: websocket\r\n" +
                    "Connection: Upgrade\r\n" +
                    "Sec-WebSocket-Accept: WRONGKEY==\r\n\r\n");
                await stream.WriteAsync(resp, 0, resp.Length, ct).ConfigureAwait(false);
            }, cts.Token);

            using var ws = new BifrostWebSocket();
            await Assert.ThrowsAsync<WebSocketException>(
                () => ws.ConnectAsync(new Uri($"ws://127.0.0.1:{port}/"), cts.Token));
        }

        // ------------------------------------------------------------------
        // SubProtocol negotiation
        // ------------------------------------------------------------------

        [Fact]
        public async Task ConnectAsync_SubProtocol_NegotiatedCorrectly()
        {
            const string proto = "chat";
            using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(10));
            int port = await TestServer.ServeWebSocket(expectedSubProtocol: proto, ct: cts.Token);

            using var ws = new BifrostWebSocket();
            ws.Options.AddSubProtocol(proto);
            await ws.ConnectAsync(new Uri($"ws://127.0.0.1:{port}/"), cts.Token)
                .ConfigureAwait(false);

            Assert.Equal(proto, ws.SubProtocol);
        }

        // ------------------------------------------------------------------
        // SendAsync / ReceiveAsync
        // ------------------------------------------------------------------

        [Fact]
        public async Task SendAsync_TextFrame_DeliveredToServer()
        {
            string received = null;
            using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(10));

            int port = await TestServer.ServeWebSocket(afterUpgrade: async (stream, ct) =>
            {
                // Read one masked client frame
                var header = new byte[2];
                await ReadExact(stream, header, ct).ConfigureAwait(false);
                int length = header[1] & 0x7F;
                if (length == 126)
                {
                    var ext = new byte[2];
                    await ReadExact(stream, ext, ct).ConfigureAwait(false);
                    length = (ext[0] << 8) | ext[1];
                }
                var mask = new byte[4];
                await ReadExact(stream, mask, ct).ConfigureAwait(false);
                var payload = new byte[length];
                await ReadExact(stream, payload, ct).ConfigureAwait(false);
                for (int i = 0; i < payload.Length; i++)
                    payload[i] ^= mask[i % 4];
                received = Encoding.UTF8.GetString(payload);
            }, ct: cts.Token);

            using var ws = new BifrostWebSocket();
            await ws.ConnectAsync(new Uri($"ws://127.0.0.1:{port}/"), cts.Token)
                .ConfigureAwait(false);

            byte[] data = Encoding.UTF8.GetBytes("hello server");
            await ws.SendAsync(
                new ArraySegment<byte>(data),
                WebSocketMessageType.Text,
                endOfMessage: true,
                cts.Token).ConfigureAwait(false);

            // Give the server goroutine a moment to read
            await Task.Delay(200, cts.Token).ConfigureAwait(false);
            Assert.Equal("hello server", received);
        }

        [Fact]
        public async Task ReceiveAsync_TextFrame_ReturnsCorrectData()
        {
            const string message = "hello client";
            using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(10));

            int port = await TestServer.ServeWebSocket(afterUpgrade: async (stream, ct) =>
            {
                byte[] frame = TestServer.BuildServerFrame(message);
                await stream.WriteAsync(frame, 0, frame.Length, ct).ConfigureAwait(false);
                await stream.FlushAsync(ct).ConfigureAwait(false);
                // Keep the stream open briefly so the client can read
                await Task.Delay(300, ct).ConfigureAwait(false);
            }, ct: cts.Token);

            using var ws = new BifrostWebSocket();
            await ws.ConnectAsync(new Uri($"ws://127.0.0.1:{port}/"), cts.Token)
                .ConfigureAwait(false);

            var buf = new byte[256];
            var result = await ws.ReceiveAsync(
                new ArraySegment<byte>(buf), cts.Token).ConfigureAwait(false);

            Assert.Equal(WebSocketMessageType.Text, result.MessageType);
            Assert.True(result.EndOfMessage);
            string text = Encoding.UTF8.GetString(buf, 0, result.Count);
            Assert.Equal(message, text);
        }

        [Fact]
        public async Task ReceiveAsync_CloseFrame_ReturnsCloseMessageType()
        {
            using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(10));

            int port = await TestServer.ServeWebSocket(afterUpgrade: async (stream, ct) =>
            {
                byte[] frame = TestServer.BuildCloseFrame(1000);
                await stream.WriteAsync(frame, 0, frame.Length, ct).ConfigureAwait(false);
                await stream.FlushAsync(ct).ConfigureAwait(false);
                await Task.Delay(300, ct).ConfigureAwait(false);
            }, ct: cts.Token);

            using var ws = new BifrostWebSocket();
            await ws.ConnectAsync(new Uri($"ws://127.0.0.1:{port}/"), cts.Token)
                .ConfigureAwait(false);

            var buf = new byte[256];
            var result = await ws.ReceiveAsync(
                new ArraySegment<byte>(buf), cts.Token).ConfigureAwait(false);

            Assert.Equal(WebSocketMessageType.Close, result.MessageType);
        }

        // ------------------------------------------------------------------
        // Send on non-open socket
        // ------------------------------------------------------------------

        [Fact]
        public async Task SendAsync_BeforeConnect_Throws()
        {
            using var ws = new BifrostWebSocket();
            byte[] data = Encoding.UTF8.GetBytes("test");
            await Assert.ThrowsAsync<WebSocketException>(
                () => ws.SendAsync(
                    new ArraySegment<byte>(data),
                    WebSocketMessageType.Text,
                    true,
                    CancellationToken.None));
        }

        [Fact]
        public async Task SendAsync_CloseMessageType_Throws()
        {
            using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(10));
            int port = await TestServer.ServeWebSocket(ct: cts.Token);

            using var ws = new BifrostWebSocket();
            await ws.ConnectAsync(new Uri($"ws://127.0.0.1:{port}/"), cts.Token)
                .ConfigureAwait(false);

            byte[] data = new byte[0];
            await Assert.ThrowsAsync<ArgumentException>(
                () => ws.SendAsync(
                    new ArraySegment<byte>(data),
                    WebSocketMessageType.Close,
                    true,
                    cts.Token));
        }

        // ------------------------------------------------------------------
        // CloseAsync / Abort / Dispose
        // ------------------------------------------------------------------

        [Fact]
        public async Task CloseAsync_Open_StateBecomesClosedAndDoesNotThrow()
        {
            using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(10));
            int port = await TestServer.ServeWebSocket(ct: cts.Token);

            using var ws = new BifrostWebSocket();
            await ws.ConnectAsync(new Uri($"ws://127.0.0.1:{port}/"), cts.Token)
                .ConfigureAwait(false);

            await ws.CloseAsync(WebSocketCloseStatus.NormalClosure, "bye", cts.Token)
                .ConfigureAwait(false);

            Assert.Equal(WebSocketState.Closed, ws.State);
        }

        [Fact]
        public async Task CloseAsync_AlreadyClosed_DoesNotThrow()
        {
            using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(10));
            int port = await TestServer.ServeWebSocket(ct: cts.Token);

            using var ws = new BifrostWebSocket();
            await ws.ConnectAsync(new Uri($"ws://127.0.0.1:{port}/"), cts.Token)
                .ConfigureAwait(false);

            await ws.CloseAsync(WebSocketCloseStatus.NormalClosure, "bye", cts.Token)
                .ConfigureAwait(false);

            // Second close on already-closed must not throw
            var ex = await Record.ExceptionAsync(
                () => ws.CloseAsync(WebSocketCloseStatus.NormalClosure, "bye2", cts.Token));
            Assert.Null(ex);
        }

        [Fact]
        public void Abort_BeforeConnect_DoesNotThrow()
        {
            using var ws = new BifrostWebSocket();
            var ex = Record.Exception(() => ws.Abort());
            Assert.Null(ex);
        }

        [Fact]
        public async Task Abort_Open_StateBecomesAborted()
        {
            using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(10));
            int port = await TestServer.ServeWebSocket(ct: cts.Token);

            using var ws = new BifrostWebSocket();
            await ws.ConnectAsync(new Uri($"ws://127.0.0.1:{port}/"), cts.Token)
                .ConfigureAwait(false);

            ws.Abort();
            Assert.Equal(WebSocketState.Aborted, ws.State);
        }

        [Fact]
        public void Dispose_CalledTwice_DoesNotThrow()
        {
            var ws = new BifrostWebSocket();
            ws.Dispose();
            var ex = Record.Exception(() => ws.Dispose());
            Assert.Null(ex);
        }

        // ------------------------------------------------------------------
        // Options / headers
        // ------------------------------------------------------------------

        [Fact]
        public async Task Options_SetRequestHeader_SentInUpgrade()
        {
            string receivedRequest = null;
            using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(10));

            int port = await TestServer.RunOnceAsync(async (stream, ct) =>
            {
                var buf = new byte[4096];
                int n = await stream.ReadAsync(buf, 0, buf.Length, ct).ConfigureAwait(false);
                receivedRequest = Encoding.ASCII.GetString(buf, 0, n);

                // Extract key and respond properly so ConnectAsync completes
                string key = "";
                foreach (var line in receivedRequest.Split(new[] { "\r\n" }, StringSplitOptions.None))
                {
                    if (line.StartsWith("Sec-WebSocket-Key:", StringComparison.OrdinalIgnoreCase))
                    {
                        key = line.Substring("Sec-WebSocket-Key:".Length).Trim();
                        break;
                    }
                }
                string accept = ComputeAccept(key);
                byte[] resp = Encoding.ASCII.GetBytes(
                    "HTTP/1.1 101 Switching Protocols\r\n" +
                    "Upgrade: websocket\r\nConnection: Upgrade\r\n" +
                    $"Sec-WebSocket-Accept: {accept}\r\n\r\n");
                await stream.WriteAsync(resp, 0, resp.Length, ct).ConfigureAwait(false);
                await Task.Delay(200, ct).ConfigureAwait(false);
            }, cts.Token);

            using var ws = new BifrostWebSocket();
            ws.Options.SetRequestHeader("X-Custom-Header", "test-value");

            await ws.ConnectAsync(new Uri($"ws://127.0.0.1:{port}/"), cts.Token)
                .ConfigureAwait(false);

            Assert.Contains("X-Custom-Header: test-value", receivedRequest);
        }

        [Fact]
        public void Options_SetRequestHeader_CrlfInValue_Throws()
        {
            using var ws = new BifrostWebSocket();
            // The header injection check is inside SanitizeHeader, called during upgrade.
            // We verify it by trying to connect and expecting a throw.
            ws.Options.SetRequestHeader("X-Evil", "val\r\nInjected: x");

            // The throw happens when we actually write the upgrade request.
            // Use a local listener so the test doesn't go to the network.
            Assert.ThrowsAnyAsync<Exception>(async () =>
            {
                using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(5));
                int port = await TestServer.RunOnceAsync(
                    async (s, ct) => await Task.Delay(500, ct), cts.Token);
                await ws.ConnectAsync(new Uri($"ws://127.0.0.1:{port}/"), cts.Token);
            });
        }

        // ------------------------------------------------------------------
        // Helpers
        // ------------------------------------------------------------------

        private static async Task ReadExact(Stream stream, byte[] buf, CancellationToken ct)
        {
            int read = 0;
            while (read < buf.Length)
            {
                int n = await stream.ReadAsync(buf, read, buf.Length - read, ct)
                    .ConfigureAwait(false);
                if (n == 0) throw new EndOfStreamException();
                read += n;
            }
        }

        private static string ComputeAccept(string key)
        {
            const string Magic = "258EAFA5-E914-47DA-95CA-C5AB0DC85B11";
            using var sha1 = SHA1.Create();
            byte[] combined = Encoding.ASCII.GetBytes(key + Magic);
            return Convert.ToBase64String(sha1.ComputeHash(combined));
        }
    }

    // ---------------------------------------------------------------
    // BifrostWebSocket — NameMatches (via BifrostEngine hostname
    // validation observable behaviour)
    // ---------------------------------------------------------------

    /// <summary>
    /// These tests exercise the wildcard / exact-match hostname logic
    /// that lives inside BouncyCertAuth.NameMatches (private static).
    /// Because it is private, we test it indirectly through observable
    /// behaviour: a connection whose server sends a cert with a
    /// non-matching hostname must be rejected.  However since we cannot
    /// spin up a real TLS server in a unit test, we validate the
    /// NameMatches logic via a thin public wrapper exposed for testing.
    /// If your project has a test-seam / InternalsVisibleTo you can
    /// call NameMatches directly; otherwise the helper below replicates
    /// the same logic so the rules are verified independently.
    /// </summary>
    public class NameMatchTests
    {
        // Replicated from BifrostTLS.BouncyCertAuth.NameMatches
        private static bool NameMatches(string pattern, string host)
        {
            if (string.IsNullOrEmpty(pattern) || string.IsNullOrEmpty(host))
                return false;

            if (string.Equals(pattern, host, StringComparison.OrdinalIgnoreCase))
                return true;

            if (!pattern.StartsWith("*.") || pattern.Length < 3)
                return false;

            string suffix = pattern.Substring(1); // ".example.com"

            int dotCount = 0;
            foreach (char c in suffix) if (c == '.') dotCount++;
            if (dotCount < 2) return false;

            if (!host.EndsWith(suffix, StringComparison.OrdinalIgnoreCase))
                return false;

            string leftLabel = host.Substring(0, host.Length - suffix.Length);
            return leftLabel.Length > 0 && leftLabel.IndexOf('.') < 0;
        }

        [Theory]
        [InlineData("skymu.app", "skymu.app", true)]
        [InlineData("skymu.app", "SKYMU.APP", true)]  // case-insensitive
        [InlineData("skymu.app", "evil.com", false)]
        [InlineData("*.skymu.app", "api.skymu.app", true)]
        [InlineData("*.skymu.app", "skymu.app", false)] // wildcard needs left label
        [InlineData("*.skymu.app", "a.b.skymu.app", false)] // only one label allowed
        [InlineData("*.co.uk", "skymu.co.uk", false)] // suffix has only 2 dots → rejected
        [InlineData("", "skymu.app", false)]
        [InlineData("skymu.app", "", false)]
        [InlineData("*.skymu.app", "API.SKYMU.APP", true)]  // wildcard + case-insensitive
        [InlineData("notawildcard.app", "sub.notawildcard.app", false)]
        public void NameMatches_Theory(string pattern, string host, bool expected)
        {
            Assert.Equal(expected, NameMatches(pattern, host));
        }
    }
}