/*==========================================================*/
// Copyright © The Skymu Team and other contributors.
// For any inquiries or concerns, email contact@skymu.app.
/*==========================================================*/
// Modification or redistribution of this code is governed
// by the terms set out in the project license agreement.
// If you do not comply with those terms, you may not
// modify or distribute any original code from the project.
/*==========================================================*/
// License: https://skymu.app/legal/license
// SPDX-License-Identifier: AGPL-3.0-or-later
/*==========================================================*/
// Portions of Skymu's tests may be generated by a tool.
// As such, this code is not included in the Skymu application
// and is only used for testing during development.
/*==========================================================*/

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Skymu.Databases;
using Xunit;
using Yggdrasil.Enumerations;
using Yggdrasil.Models;

namespace Skymu.Tests
{
    // ---------------------------------------------------------------
    // Fixture — creates a fresh temp folder + DatabaseManager for
    // each test class, then deletes it on disposal.
    //
    // DatabaseManager's custom_db_folder constructor parameter bypasses
    // the appdata path and Universal.Plugin dependency entirely, so all
    // tests here are self-contained and require no WPF / STA thread.
    // ---------------------------------------------------------------

    public sealed class DatabaseFixture : IDisposable
    {
        public string FolderPath { get; }
        public DatabaseManager DB { get; }

        public DatabaseFixture()
        {
            FolderPath = Path.Combine(
                Path.GetTempPath(),
                "SkymuTests_" + Guid.NewGuid().ToString("N")
            );
            Directory.CreateDirectory(FolderPath);
            DB = new DatabaseManager(user: null, custom_db_folder: FolderPath);
        }

        public void Dispose()
        {
            try { Directory.Delete(FolderPath, recursive: true); }
            catch { /* best-effort cleanup */ }
        }
    }

    // ---------------------------------------------------------------
    // Helpers shared across all test classes
    // ---------------------------------------------------------------

    internal static class Make
    {
        public static User User(
            string id = "alice",
            string username = "alice_user",
            string display = "Alice",
            string status = null,
            byte[] avatar = null)
            => new User(display, username, id, status, avatar: avatar);

        public static DirectMessage DM(
            string convoId = "dm-alice",
            string partnerId = "alice",
            int unread = 0)
        {
            var partner = User(partnerId);
            return new DirectMessage(partner, unread, convoId, DateTime.UtcNow);
        }

        public static Group Group(
            string convoId = "grp-1",
            string name = "Test Group",
            int unread = 0,
            params string[] memberIds)
        {
            var members = memberIds.Length > 0
                ? memberIds.Select(id => User(id)).ToArray()
                : new[] { User("bob"), User("charlie") };
            return new Group(name, convoId, unread, members, last_message_time: DateTime.UtcNow);
        }

        public static Message TextMessage(
            string id = "msg-1",
            string authorId = "alice",
            string text = "Hello!",
            DateTime? time = null)
            => new Message(id, User(authorId), time ?? DateTime.UtcNow, text: text);

        public static Message MessageWithImage(
            string id = "msg-img-1",
            string authorId = "alice",
            byte[] imageBytes = null,
            string imageName = "photo.jpg")
        {
            byte[] bytes = imageBytes ?? new byte[] { 0xFF, 0xD8, 0xFF, 0xE0, 0x01, 0x02 }; // minimal JPEG-like
            var attachment = new Attachment(bytes, imageName, null, AttachmentType.Image);
            var msg = new Message(id, User(authorId), DateTime.UtcNow, text: null);
            msg.Attachments = new[] { attachment };
            return msg;
        }

        public static CallStartedNotice CallStarted(string authorId = "alice", bool video = false)
            => new CallStartedNotice(User(authorId), video, DateTime.UtcNow);

        public static CallEndedNotice CallEnded(
            string authorId = "alice",
            double durationSecs = 120,
            bool video = false)
            => new CallEndedNotice(
                User(authorId),
                TimeSpan.FromSeconds(durationSecs),
                video,
                DateTime.UtcNow);
    }

    // ---------------------------------------------------------------
    // SanitizeFolderName — pure static, no DB needed
    // ---------------------------------------------------------------

    public class SanitizeFolderNameTests
    {
        [Theory]
        [InlineData("alice", "alice")]
        [InlineData("alice smith", "alice smith")]
        [InlineData("alice/smith", "alice_smith")]
        [InlineData("alice\\smith", "alice_smith")]
        [InlineData("alice:smith", "alice_smith")]
        [InlineData("alice*smith", "alice_smith")]
        [InlineData("alice?smith", "alice_smith")]
        [InlineData("alice\"smith", "alice_smith")]
        [InlineData("alice<smith>", "alice_smith_")]
        [InlineData("alice|smith", "alice_smith")]
        [InlineData("trailing. ", "trailing")]  // trailing dots and spaces stripped
        [InlineData("", "GenericAccount")]
        [InlineData("   ", "GenericAccount")]   // all whitespace → stripped → empty → fallback
        [InlineData("...", "GenericAccount")]   // only dots → stripped → empty → fallback
        public void Sanitize_ProducesExpected(string input, string expected)
        {
            string result = DatabaseManager.SanitizeFolderName(input);
            Assert.Equal(expected, result);
        }

        [Fact]
        public void Sanitize_Null_ReturnsFallback()
        {
            Assert.Equal("GenericAccount", DatabaseManager.SanitizeFolderName(null));
        }

        [Fact]
        public void Sanitize_CustomReplacement_UsedInsteadOfUnderscore()
        {
            string result = DatabaseManager.SanitizeFolderName("al/ice", replacement: "-");
            Assert.Equal("al-ice", result);
        }
    }

    // ---------------------------------------------------------------
    // DatabaseManager construction
    // ---------------------------------------------------------------

    public class DatabaseManagerConstructionTests : IDisposable
    {
        private readonly string _folder;

        public DatabaseManagerConstructionTests()
        {
            _folder = Path.Combine(Path.GetTempPath(), "SkymuTests_Ctor_" + Guid.NewGuid().ToString("N"));
            Directory.CreateDirectory(_folder);
        }

        public void Dispose()
        {
            try { Directory.Delete(_folder, recursive: true); } catch { }
        }

        [Fact]
        public void Constructor_CustomFolder_CreatesDbFile()
        {
            var db = new DatabaseManager(user: null, custom_db_folder: _folder);
            Assert.True(File.Exists(Path.Combine(_folder, "main.db")));
        }

        [Fact]
        public void Constructor_CustomFolder_CreatesConfigFile()
        {
            var db = new DatabaseManager(user: null, custom_db_folder: _folder);
            Assert.True(File.Exists(Path.Combine(_folder, "config.xml")));
        }

        [Fact]
        public void Constructor_CalledTwice_SameFolderDoesNotThrow()
        {
            // Simulates reopening the same database (e.g. after a restart).
            var db1 = new DatabaseManager(user: null, custom_db_folder: _folder);
            var ex = Record.Exception(
                () => new DatabaseManager(user: null, custom_db_folder: _folder));
            Assert.Null(ex);
        }

        [Fact]
        public void Constructor_ExposesAllTableProperties()
        {
            var db = new DatabaseManager(user: null, custom_db_folder: _folder);
            Assert.NotNull(db.Accounts);
            Assert.NotNull(db.Contacts);
            Assert.NotNull(db.Conversations);
            Assert.NotNull(db.Participants);
            Assert.NotNull(db.Messages);
        }
    }

    // ---------------------------------------------------------------
    // Contacts
    // ---------------------------------------------------------------

    public class ContactsTableTests : IDisposable
    {
        private readonly DatabaseFixture _fx = new DatabaseFixture();
        public void Dispose() => _fx.Dispose();

        [Fact]
        public void Read_EmptyDb_ReturnsEmptyArray()
        {
            var contacts = _fx.DB.Contacts.Read();
            Assert.Empty(contacts);
        }

        [Fact]
        public void Write_SingleDm_ContactIsReadBack()
        {
            var dm = Make.DM("dm-alice", "alice");
            _fx.DB.Conversations.Write(new[] { dm });   // ensures partner is written via Contacts.Write
            _fx.DB.Contacts.Write(new[] { dm });

            var contacts = _fx.DB.Contacts.Read();
            Assert.Contains(contacts, u => u.Identifier == "alice");
        }

        [Fact]
        public void ReadById_ExistingContact_ReturnsUser()
        {
            var dm = Make.DM("dm-bob", "bob");
            _fx.DB.Conversations.Write(new[] { dm });
            _fx.DB.Contacts.Write(new[] { dm });

            var user = _fx.DB.Contacts.Read("bob");
            Assert.NotNull(user);
            Assert.Equal("bob", user.Identifier);
        }

        [Fact]
        public void ReadById_MissingContact_ReturnsNull()
        {
            var user = _fx.DB.Contacts.Read("nobody");
            Assert.Null(user);
        }

        [Fact]
        public void Write_SameContactTwice_Upserts()
        {
            var dm1 = Make.DM("dm-alice", "alice");
            _fx.DB.Conversations.Write(new[] { dm1 });
            _fx.DB.Contacts.Write(new[] { dm1 });

            // Second write with an updated display name
            var updatedPartner = Make.User("alice", "alice_user", "Alice Updated");
            var dm2 = new DirectMessage(updatedPartner, 0, "dm-alice", DateTime.UtcNow);
            _fx.DB.Contacts.Write(new[] { dm2 });

            var contacts = _fx.DB.Contacts.Read();
            // There must still be only one alice
            Assert.Single(contacts.Where(u => u.Identifier == "alice"));
        }

        [Fact]
        public void Write_NumericIdentifier_RoundTripsCorrectly()
        {
            // Identifiers starting with a digit get "id-" prefixed internally.
            var partner = Make.User("123456", "num_user", "Numeric User");
            var dm = new DirectMessage(partner, 0, "dm-123456", DateTime.UtcNow);
            _fx.DB.Conversations.Write(new[] { dm });
            _fx.DB.Contacts.Write(new[] { dm });

            var user = _fx.DB.Contacts.Read("123456");
            Assert.NotNull(user);
            Assert.Equal("123456", user.Identifier);
        }

        [Fact]
        public void Write_ContactWithAvatar_AvatarBytesPreserved()
        {
            byte[] avatar = new byte[] { 0x89, 0x50, 0x4E, 0x47 }; // PNG magic
            var partner = Make.User("carol", "carol_u", "Carol", avatar: avatar);
            var dm = new DirectMessage(partner, 0, "dm-carol", DateTime.UtcNow);
            _fx.DB.Conversations.Write(new[] { dm });
            _fx.DB.Contacts.Write(new[] { dm });

            var read = _fx.DB.Contacts.Read("carol");
            Assert.NotNull(read?.Avatar);
            Assert.Equal(avatar, read.Avatar);
        }

        [Fact]
        public void Write_MultipleContacts_AllPresent()
        {
            var ids = new[] { "u1", "u2", "u3", "u4", "u5" };
            var dms = ids.Select(id => Make.DM($"dm-{id}", id)).ToArray();
            _fx.DB.Conversations.Write(dms);
            _fx.DB.Contacts.Write(dms);

            var contacts = _fx.DB.Contacts.Read();
            foreach (string id in ids)
                Assert.Contains(contacts, u => u.Identifier == id);
        }
    }

    // ---------------------------------------------------------------
    // Conversations
    // ---------------------------------------------------------------

    public class ConversationsTableTests : IDisposable
    {
        private readonly DatabaseFixture _fx = new DatabaseFixture();
        public void Dispose() => _fx.Dispose();

        [Fact]
        public void Read_EmptyDb_ReturnsEmptyArray()
        {
            Assert.Empty(_fx.DB.Conversations.Read());
        }

        [Fact]
        public void Write_DirectMessage_ReadBack()
        {
            var dm = Make.DM("dm-alice", "alice");
            _fx.DB.Conversations.Write(new[] { dm });

            var convos = _fx.DB.Conversations.Read();
            Assert.Contains(convos, c => c.Identifier == "dm-alice");
        }

        [Fact]
        public void Write_Group_ReadBack()
        {
            var grp = Make.Group(
    "grp-1",
    "My Group",
    memberIds: new[] { "bob", "charlie" });
            _fx.DB.Conversations.Write(new[] { grp });

            var convos = _fx.DB.Conversations.Read();
            Assert.Contains(convos, c => c.Identifier == "grp-1");
        }

        [Fact]
        public void ReadById_ExistingConvo_ReturnsCorrectType_DM()
        {
            var dm = Make.DM("dm-dave", "dave");
            _fx.DB.Conversations.Write(new[] { dm });

            var result = _fx.DB.Conversations.Read("dm-dave");
            Assert.NotNull(result);
            Assert.IsType<DirectMessage>(result);
        }

        [Fact]
        public void ReadById_ExistingConvo_ReturnsCorrectType_Group()
        {
            var grp = Make.Group("grp-2", "Team Chat");
            _fx.DB.Conversations.Write(new[] { grp });

            var result = _fx.DB.Conversations.Read("grp-2");
            Assert.NotNull(result);
            Assert.IsType<Group>(result);
        }

        [Fact]
        public void ReadById_Missing_ReturnsNull()
        {
            Assert.Null(_fx.DB.Conversations.Read("nonexistent-id"));
        }

        [Fact]
        public void Write_SameConversationTwice_Upserts()
        {
            var dm = Make.DM("dm-eve", "eve");
            _fx.DB.Conversations.Write(new[] { dm });
            _fx.DB.Conversations.Write(new[] { dm }); // must not throw or duplicate

            var convos = _fx.DB.Conversations.Read();
            Assert.Single(convos.Where(c => c.Identifier == "dm-eve"));
        }

        [Fact]
        public void Write_DM_PartnerIsAccessibleFromResult()
        {
            var dm = Make.DM("dm-frank", "frank");
            _fx.DB.Conversations.Write(new[] { dm });
            _fx.DB.Contacts.Write(new[] { dm });

            var result = _fx.DB.Conversations.Read("dm-frank") as DirectMessage;
            Assert.NotNull(result);
            Assert.NotNull(result.Partner);
            Assert.Equal("frank", result.Partner.Identifier);
        }

        [Fact]
        public void Write_Group_MembersAreStoredAsParticipants()
        {
            var grp = Make.Group("grp-members", "Members Test", memberIds: new[] { "x", "y", "z" });
            _fx.DB.Conversations.Write(new[] { grp });

            var result = _fx.DB.Conversations.Read("grp-members") as Group;
            Assert.NotNull(result);
            // Members come back as stubs (not in contacts), but identifiers should be present
            var memberIds = result.Members.Select(m => m.Identifier).ToArray();
            Assert.Contains("x", memberIds);
            Assert.Contains("y", memberIds);
            Assert.Contains("z", memberIds);
        }

        [Fact]
        public void Write_Mixed_DmAndGroup_BothReadBack()
        {
            var dm = Make.DM("dm-h", "h");
            var grp = Make.Group("grp-h", "Group H");
            _fx.DB.Conversations.Write(new Conversation[] { dm, grp });

            var convos = _fx.DB.Conversations.Read();
            Assert.Contains(convos, c => c.Identifier == "dm-h");
            Assert.Contains(convos, c => c.Identifier == "grp-h");
        }
    }

    // ---------------------------------------------------------------
    // Messages
    // ---------------------------------------------------------------

    public class MessagesTableTests : IDisposable
    {
        private readonly DatabaseFixture _fx = new DatabaseFixture();
        public void Dispose() => _fx.Dispose();

        private void SeedConvo(Conversation convo)
        {
            _fx.DB.Conversations.Write(new[] { convo });
            if (convo is DirectMessage dm)
                _fx.DB.Contacts.Write(new[] { dm });
        }

        [Fact]
        public void Read_EmptyConvo_ReturnsEmptyList()
        {
            var dm = Make.DM("dm-empty", "alice");
            SeedConvo(dm);

            var messages = _fx.DB.Messages.Read(dm);
            Assert.Empty(messages);
        }

        [Fact]
        public void WriteRow_TextMessage_ReadBackCorrectly()
        {
            var dm = Make.DM("dm-msg1", "alice");
            SeedConvo(dm);
            var msg = Make.TextMessage("m1", "alice", "Hello there!");

            _fx.DB.Messages.WriteRow(msg, dm);

            var messages = _fx.DB.Messages.Read(dm);
            Assert.Single(messages);
            var read = Assert.IsType<Message>(messages[0]);
            Assert.Equal("Hello there!", read.Text);
        }

        [Fact]
        public void Write_MultipleMessages_OrderedAscending()
        {
            var dm = Make.DM("dm-order", "alice");
            SeedConvo(dm);

            var t0 = DateTime.UtcNow.AddMinutes(-5);
            var t1 = DateTime.UtcNow.AddMinutes(-3);
            var t2 = DateTime.UtcNow.AddMinutes(-1);

            var msgs = new ConversationItem[]
            {
                new Message("m-a", Make.User("alice"), t0, text: "First"),
                new Message("m-b", Make.User("alice"), t1, text: "Second"),
                new Message("m-c", Make.User("alice"), t2, text: "Third"),
            };
            _fx.DB.Messages.Write(msgs, dm);

            var result = _fx.DB.Messages.Read(dm);
            Assert.Equal(3, result.Count);
            Assert.Equal("First", ((Message)result[0]).Text);
            Assert.Equal("Second", ((Message)result[1]).Text);
            Assert.Equal("Third", ((Message)result[2]).Text);
        }

        [Fact]
        public void Write_SameMessage_Upserts()
        {
            var dm = Make.DM("dm-upsert", "alice");
            SeedConvo(dm);
            var msg = Make.TextMessage("m-dup", "alice", "Original");

            _fx.DB.Messages.WriteRow(msg, dm);
            var updated = new Message("m-dup", Make.User("alice"), msg.Time, text: "Updated");
            _fx.DB.Messages.WriteRow(updated, dm);

            var result = _fx.DB.Messages.Read(dm);
            Assert.Single(result);
            Assert.Equal("Updated", ((Message)result[0]).Text);
        }

        [Fact]
        public void Read_LimitParameter_RespectsLimit()
        {
            var dm = Make.DM("dm-limit", "alice");
            SeedConvo(dm);

            var msgs = Enumerable.Range(1, 10)
                .Select(i => (ConversationItem)new Message(
                    $"m-{i}", Make.User("alice"),
                    DateTime.UtcNow.AddMinutes(-10 + i),
                    text: $"msg {i}"))
                .ToArray();
            _fx.DB.Messages.Write(msgs, dm);

            var result = _fx.DB.Messages.Read(dm, limit: 5);
            Assert.Equal(5, result.Count);
        }

        [Fact]
        public void Read_BeforeTimestamp_ReturnsOnlyOlderMessages()
        {
            var dm = Make.DM("dm-before", "alice");
            SeedConvo(dm);

            var cutoff = DateTime.UtcNow;
            var older = new Message("m-old", Make.User("alice"), cutoff.AddMinutes(-10), text: "Old");
            var newer = new Message("m-new", Make.User("alice"), cutoff.AddMinutes(10), text: "New");
            _fx.DB.Messages.Write(new ConversationItem[] { older, newer }, dm);

            long cutoffMs = new DateTimeOffset(cutoff).ToUnixTimeMilliseconds();
            var result = _fx.DB.Messages.Read(dm, limit: 0, beforeTimestampMs: cutoffMs);

            Assert.Single(result);
            Assert.Equal("Old", ((Message)result[0]).Text);
        }

        [Fact]
        public void Write_CallStartedNotice_ReadBackAsCallStarted()
        {
            var dm = Make.DM("dm-call", "alice");
            SeedConvo(dm);
            var call = Make.CallStarted("alice");

            _fx.DB.Messages.Write(new ConversationItem[] { call }, dm);

            var result = _fx.DB.Messages.Read(dm);
            Assert.Single(result);
            Assert.IsType<CallStartedNotice>(result[0]);
        }

        [Fact]
        public void Write_CallEndedNotice_ReadBackAsCallEnded()
        {
            var dm = Make.DM("dm-callend", "alice");
            SeedConvo(dm);
            var call = Make.CallEnded("alice", durationSecs: 65);

            _fx.DB.Messages.Write(new ConversationItem[] { call }, dm);

            var result = _fx.DB.Messages.Read(dm);
            Assert.Single(result);
            var ended = Assert.IsType<CallEndedNotice>(result[0]);
            Assert.Equal(65, ended.Duration.TotalSeconds, precision: 0);
        }

        [Fact]
        public void WriteRow_ImageAttachment_FileWrittenToDisk()
        {
            var dm = Make.DM("dm-img", "alice");
            SeedConvo(dm);
            var msg = Make.MessageWithImage("m-img", "alice");

            _fx.DB.Messages.WriteRow(msg, dm);

            string mediaDir = Path.Combine(_fx.FolderPath, "Media");
            Assert.True(Directory.Exists(mediaDir));
            Assert.NotEmpty(Directory.GetFiles(mediaDir));
        }

        [Fact]
        public void Read_ImageAttachment_RestoredOnRead()
        {
            var dm = Make.DM("dm-imgread", "alice");
            SeedConvo(dm);
            byte[] imgBytes = new byte[] { 0xFF, 0xD8, 0xFF, 0xE0, 0x00, 0x10 };
            var msg = Make.MessageWithImage("m-imgread", "alice", imgBytes);

            _fx.DB.Messages.WriteRow(msg, dm);

            var result = _fx.DB.Messages.Read(dm);
            var readMsg = Assert.IsType<Message>(result[0]);
            Assert.NotNull(readMsg.Attachments);
            Assert.NotEmpty(readMsg.Attachments);
            Assert.Equal(imgBytes, readMsg.Attachments[0].File);
        }

        [Fact]
        public void Write_MessageWithParent_ParentResolvable()
        {
            var dm = Make.DM("dm-reply", "alice");
            SeedConvo(dm);

            var parent = Make.TextMessage("m-parent", "alice", "Parent message",
                time: DateTime.UtcNow.AddMinutes(-2));
            var reply = new Message("m-reply", Make.User("alice"),
                DateTime.UtcNow, text: "This is a reply");
            reply.ParentMessage = parent;

            _fx.DB.Messages.WriteRow(parent, dm);
            _fx.DB.Messages.WriteRow(reply, dm);

            var result = _fx.DB.Messages.Read(dm);
            var replyMsg = result.OfType<Message>()
                                 .FirstOrDefault(m => m.Identifier == "m-reply");
            Assert.NotNull(replyMsg);
            Assert.NotNull(replyMsg.ParentMessage);
            Assert.Equal("m-parent", replyMsg.ParentMessage.Identifier);
        }

        [Fact]
        public void Write_ToGroupConversation_MessagesReadBack()
        {
            var grp = Make.Group(
    "grp-msg",
    "Chat Group",
    memberIds: new[] { "bob", "charlie" });
            _fx.DB.Conversations.Write(new[] { grp });

            var msgs = new ConversationItem[]
            {
                Make.TextMessage("gm1", "bob",     "Hey everyone"),
                Make.TextMessage("gm2", "charlie", "Hey!"),
            };
            _fx.DB.Messages.Write(msgs, grp);

            var result = _fx.DB.Messages.Read(grp);
            Assert.Equal(2, result.Count);
        }

        [Fact]
        public void Write_LastActivityTimestamp_UpdatedOnConversation()
        {
            var dm = Make.DM("dm-ts", "alice");
            SeedConvo(dm);

            _fx.DB.Messages.WriteRow(
                Make.TextMessage("m-ts", "alice", "ping"),
                dm);

            // After writing, the conversation's last_activity_timestamp should be set.
            var convo = _fx.DB.Conversations.Read("dm-ts");
            Assert.NotNull(convo);
            // DateTime.MinValue means it was never set; any real value means it was updated.
            Assert.NotEqual(DateTime.MinValue, convo.LastMessageTime);
        }

        [Fact]
        public void Write_EmptyItems_DoesNotThrow()
        {
            var dm = Make.DM("dm-empty-write", "alice");
            SeedConvo(dm);

            var ex = Record.Exception(
                () => _fx.DB.Messages.Write(Array.Empty<ConversationItem>(), dm));
            Assert.Null(ex);
        }

        [Fact]
        public void Write_UnknownItemType_IsSkippedGracefully()
        {
            var dm = Make.DM("dm-unknown", "alice");
            SeedConvo(dm);

            // ConversationItem subclass that isn't Message/CallStarted/CallEnded
            var unknownItem = new UnknownItem("x-1", Make.User("alice"), DateTime.UtcNow);
            var ex = Record.Exception(
                () => _fx.DB.Messages.Write(new ConversationItem[] { unknownItem }, dm));
            Assert.Null(ex);

            Assert.Empty(_fx.DB.Messages.Read(dm));
        }
    }

    // ---------------------------------------------------------------
    // Accounts
    // ---------------------------------------------------------------

    public class AccountsTableTests : IDisposable
    {
        private readonly DatabaseFixture _fx = new DatabaseFixture();
        public void Dispose() => _fx.Dispose();

        [Fact]
        public void Write_Account_DoesNotThrow()
        {
            var user = Make.User("myaccount", "myaccount_u", "My Account");
            var ex = Record.Exception(() => _fx.DB.Accounts.Write(user));
            Assert.Null(ex);
        }

        [Fact]
        public void Write_SameAccountTwice_Upserts()
        {
            var user = Make.User("acc1", "acc1_u", "Account One");
            _fx.DB.Accounts.Write(user);

            var ex = Record.Exception(() => _fx.DB.Accounts.Write(user));
            Assert.Null(ex);
        }

        [Fact]
        public void Write_AccountWithAvatar_DoesNotThrow()
        {
            byte[] avatar = new byte[] { 0x00, 0xFF, 0xD8, 0xFF }; // already has 0x00 prefix
            var user = Make.User("acc-av", "acc_av_u", "Avatar Account", avatar: avatar);
            var ex = Record.Exception(() => _fx.DB.Accounts.Write(user));
            Assert.Null(ex);
        }

        [Fact]
        public void Write_AccountWithNumericIdentifier_DoesNotThrow()
        {
            var user = Make.User("999888", "num_acc", "Numeric Account");
            var ex = Record.Exception(() => _fx.DB.Accounts.Write(user));
            Assert.Null(ex);
        }
    }

    // ---------------------------------------------------------------
    // Version / config file handling
    // ---------------------------------------------------------------

    public class DatabaseVersionTests : IDisposable
    {
        private readonly string _folder;

        public DatabaseVersionTests()
        {
            _folder = Path.Combine(
                Path.GetTempPath(),
                "SkymuTests_Version_" + Guid.NewGuid().ToString("N"));
            Directory.CreateDirectory(_folder);
        }

        public void Dispose()
        {
            try { Directory.Delete(_folder, recursive: true); } catch { }
        }

        [Fact]
        public void Constructor_CreatesValidXmlConfigFile()
        {
            new DatabaseManager(user: null, custom_db_folder: _folder);

            string configPath = Path.Combine(_folder, "config.xml");
            Assert.True(File.Exists(configPath));

            var doc = System.Xml.Linq.XDocument.Load(configPath);
            Assert.NotNull(doc.Root);
            var versionEl = doc.Root.Element("DatabaseVersion");
            Assert.NotNull(versionEl);
            Assert.True(int.TryParse(versionEl.Value, out int v) && v >= 1);
        }

        [Fact]
        public void Constructor_CorruptConfigFile_WipesAndRecreates()
        {
            // Write a corrupt config — constructor should wipe and rebuild rather than crash.
            string configPath = Path.Combine(_folder, "config.xml");
            File.WriteAllText(configPath, "THIS IS NOT XML <<<");

            var ex = Record.Exception(
                () => new DatabaseManager(user: null, custom_db_folder: _folder));
            Assert.Null(ex);
            Assert.True(File.Exists(configPath));

            // Should now be valid XML
            var doc = System.Xml.Linq.XDocument.Load(configPath);
            Assert.NotNull(doc.Root?.Element("DatabaseVersion"));
        }

        [Fact]
        public void Constructor_StaleVersionInConfig_WipesDb()
        {
            // First, create a DB with some data.
            var db = new DatabaseManager(user: null, custom_db_folder: _folder);
            var dm = Make.DM("dm-a", "a");
            db.Conversations.Write(new[] { dm });

            // Now write a config claiming version 0 (older than current).
            string configPath = Path.Combine(_folder, "config.xml");
            new System.Xml.Linq.XDocument(
                new System.Xml.Linq.XElement("SkymuDatabase",
                    new System.Xml.Linq.XElement("DatabaseVersion", 0))
            ).Save(configPath);

            // Recreating the manager should wipe the old database.
            var db2 = new DatabaseManager(user: null, custom_db_folder: _folder);
            Assert.Empty(db2.Conversations.Read());
        }
    }

    // ---------------------------------------------------------------
    // Stub for unknown ConversationItem types used in skip test
    // ---------------------------------------------------------------

    internal sealed class UnknownItem : ConversationItem
    {
        internal User Author;
        public UnknownItem(string id, User author, DateTime time)
        {
            Time = time;
            Identifier = id;
            Author = author;
        }
    }
}