/*==========================================================*/
// Copyright © The Skymu Team and other contributors.
// For any inquiries or concerns, email contact@skymu.app.
/*==========================================================*/
// Modification or redistribution of this code is governed
// by the terms set out in the project license agreement.
// If you do not comply with those terms, you may not
// modify or distribute any original code from the project.
/*==========================================================*/
// License: https://skymu.app/legal/license
// SPDX-License-Identifier: AGPL-3.0-or-later
/*==========================================================*/
// Portions of Skymu's tests may be generated by a tool.
// As such, this code is not included in the Skymu application
// and is only used for testing during development.
/*==========================================================*/

using System;
using System.Linq;
using System.Threading;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Media;
using Skymu.Formatting;
using Xunit;

namespace Skymu.Tests
{
    public class FormatterTests
    {
        // -------------------------------------------------------
        // STA helpers
        // -------------------------------------------------------

        /// <summary>
        /// Runs <paramref name="func"/> on a fresh STA thread and returns its result.
        /// Both construction AND assertions must happen inside the same STA call so
        /// WPF never raises "a different thread owns this object".
        /// </summary>
        private static T RunSta<T>(Func<T> func)
        {
            T result = default;
            Exception ex = null;

            var thread = new Thread(() =>
            {
                try { result = func(); }
                catch (Exception e) { ex = e; }
            });

            thread.SetApartmentState(ApartmentState.STA);
            thread.Start();
            thread.Join();

            if (ex != null) System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(ex).Throw();
            return result;
        }

        /// <summary>Runs an assertion-only action on an STA thread.</summary>
        private static void RunSta(Action action) => RunSta<int>(() => { action(); return 0; });

        private static string FlattenInlines(InlineCollection inlines)
            => string.Concat(inlines.OfType<Run>().Select(r => r.Text));

        private static bool HasNestedHyperlink(InlineCollection inlines)
        {
            foreach (var inline in inlines)
            {
                if (inline is Hyperlink) return true;
                if (inline is Span span && HasNestedHyperlink(span.Inlines))
                    return true;
            }
            return false;
        }

        // -------------------------------------------------------
        // Basic
        // -------------------------------------------------------

        [Fact]
        public void Parse_NullOrEmpty_DoesNotThrow()
        {
            // Parse("") must not throw; result must be non-null
            RunSta(() =>
            {
                var tb = Formatter.Parse("");
                Assert.NotNull(tb);
            });
        }

        [Fact]
        public void Parse_ReturnsTextBlock()
        {
            RunSta(() =>
            {
                var tb = Formatter.Parse("test");
                Assert.IsType<TextBlock>(tb);
            });
        }

        [Fact]
        public void Parse_DoNotFormat_SetsTextDirectly()
        {
            // All access to tb must happen on the same STA thread that created it.
            RunSta(() =>
            {
                var tb = Formatter.Parse("hello world", doNotFormat: true);
                Assert.Equal("hello world", tb.Text);
            });
        }

        [Fact]
        public void Parse_DoNotFormat_HasNoInlines()
        {
            RunSta(() =>
            {
                var tb = Formatter.Parse("**bold**", doNotFormat: true);
                // doNotFormat sets .Text directly — the Inlines collection must be empty
                Assert.Empty(tb.Inlines);
            });
        }

        [Fact]
        public void Parse_PlainText_ProducesRun()
        {
            // Plain text that contains no URL or emoji goes through
            // AddTextOrLinkOrClickable → ProcessTextWithEmoji.
            // Universal.Plugin may be null in test environment; if it throws
            // we still get "some inlines" from earlier blocks, so we only
            // assert the TextBlock itself is non-null and is the right type.
            RunSta(() =>
            {
                var tb = Formatter.Parse("hello world");
                Assert.NotNull(tb);
                Assert.IsType<TextBlock>(tb);
            });
        }

        // -------------------------------------------------------
        // Markdown formatting
        // The emphasis / heading paths do NOT call AddTextOrLinkOrClickable
        // directly before the span is added, so they are safe even when
        // Universal.Plugin is null — the inner LiteralInline does call it,
        // but the Span itself is added first.  We therefore assert on the
        // Span properties, which are always set before any possible crash.
        // -------------------------------------------------------

        [Fact]
        public void Parse_Bold_ProducesBoldSpan()
        {
            RunSta(() =>
            {
                var tb = Formatter.Parse("**bold text**");
                var spans = tb.Inlines.OfType<Span>();
                Assert.True(spans.Any(s => s.FontWeight == FontWeights.Bold),
                    "Expected at least one bold Span.");
            });
        }

        [Fact]
        public void Parse_Italic_ProducesItalicSpan()
        {
            RunSta(() =>
            {
                var tb = Formatter.Parse("*italic text*");
                var spans = tb.Inlines.OfType<Span>();
                Assert.True(spans.Any(s => s.FontStyle == FontStyles.Italic),
                    "Expected at least one italic Span.");
            });
        }

        [Fact]
        public void Parse_Strikethrough_ProducesStrikethroughSpan()
        {
            RunSta(() =>
            {
                var tb = Formatter.Parse("~~strikethrough~~");
                var spans = tb.Inlines.OfType<Span>();
                Assert.True(spans.Any(s => s.TextDecorations == TextDecorations.Strikethrough),
                    "Expected at least one strikethrough Span.");
            });
        }

        [Fact]
        public void Parse_Underline_ProducesUnderlineSpan()
        {
            RunSta(() =>
            {
                var tb = Formatter.Parse("++underline++");
                var spans = tb.Inlines.OfType<Span>();
                Assert.True(spans.Any(s => s.TextDecorations == TextDecorations.Underline),
                    "Expected at least one underline Span.");
            });
        }

        [Fact]
        public void Parse_Highlight_ProducesYellowBackground()
        {
            RunSta(() =>
            {
                var tb = Formatter.Parse("==highlight==");
                var spans = tb.Inlines.OfType<Span>();
                Assert.True(spans.Any(s => s.Background == Brushes.Yellow),
                    "Expected at least one yellow-background Span.");
            });
        }

        [Fact]
        public void Parse_BoldItalic_ProducesBothStyles()
        {
            RunSta(() =>
            {
                var tb = Formatter.Parse("***bolditalic***");
                var spans = tb.Inlines.OfType<Span>();
                Assert.True(
                    spans.Any(s =>
                        s.FontWeight == FontWeights.Bold &&
                        s.FontStyle == FontStyles.Italic),
                    "Expected at least one Span that is both bold and italic.");
            });
        }

        // -------------------------------------------------------
        // Headings
        // -------------------------------------------------------

        [Fact]
        public void Parse_H1_ProducesLargeSpan()
        {
            RunSta(() =>
            {
                var tb = Formatter.Parse("# Heading 1");
                var spans = tb.Inlines.OfType<Span>();
                Assert.True(spans.Any(s => s.FontSize == 24),
                    "Expected H1 Span with FontSize 24.");
            });
        }

        [Fact]
        public void Parse_H2_ProducesMediumSpan()
        {
            RunSta(() =>
            {
                var tb = Formatter.Parse("## Heading 2");
                var spans = tb.Inlines.OfType<Span>();
                Assert.True(spans.Any(s => s.FontSize == 20),
                    "Expected H2 Span with FontSize 20.");
            });
        }

        [Fact]
        public void Parse_H3_ProducesSmallerSpan()
        {
            RunSta(() =>
            {
                var tb = Formatter.Parse("### Heading 3");
                var spans = tb.Inlines.OfType<Span>();
                Assert.True(spans.Any(s => s.FontSize == 16),
                    "Expected H3 Span with FontSize 16.");
            });
        }

        // -------------------------------------------------------
        // Links — these paths work even without Universal.Plugin
        // because link detection is done by Markdig (LinkInline),
        // not by AddTextOrLinkOrClickable.
        // -------------------------------------------------------

        [Fact]
        public void Parse_Url_ProducesHyperlink()
        {
            RunSta(() =>
            {
                var tb = Formatter.Parse("https://skymu.app");
                Assert.True(
                    tb.Inlines.OfType<Hyperlink>().Any() || HasNestedHyperlink(tb.Inlines),
                    "Expected at least one Hyperlink for a bare URL.");
            });
        }

        [Fact]
        public void Parse_MarkdownLink_ProducesHyperlinkWithCorrectUri()
        {
            RunSta(() =>
            {
                var tb = Formatter.Parse("[Skymu](https://skymu.app)");
                var links = tb.Inlines.OfType<Hyperlink>().ToList();
                Assert.True(
                    links.Any(h => h.NavigateUri?.Host == "skymu.app"),
                    "Expected a Hyperlink whose NavigateUri.Host is 'skymu.app'.");
            });
        }

        [Fact]
        public void Parse_MismatchedDisplayUrl_ShowsWarning()
        {
            RunSta(() =>
            {
                // Display text looks like a URL but points to a different host.
                // Formatter appends a warning Run containing the real destination.
                var tb = Formatter.Parse("[https://evil.com](https://skymu.app)");
                string flat = FlattenInlines(tb.Inlines);
                Assert.True(flat.Contains("skymu.app"),
                    "Expected warning Run to contain the real destination host.");
            });
        }

        // -------------------------------------------------------
        // Code
        // -------------------------------------------------------

        [Fact]
        public void Parse_InlineCode_ProducesInlineUIContainer()
        {
            RunSta(() =>
            {
                var tb = Formatter.Parse("`code`");
                Assert.True(
                    tb.Inlines.OfType<InlineUIContainer>().Any(),
                    "Expected an InlineUIContainer for inline code.");
            });
        }

        [Fact]
        public void Parse_FencedCodeBlock_ProducesInlineUIContainer()
        {
            RunSta(() =>
            {
                var tb = Formatter.Parse("```\ncode block\n```");
                Assert.True(
                    tb.Inlines.OfType<InlineUIContainer>().Any(),
                    "Expected an InlineUIContainer for a fenced code block.");
            });
        }

        // -------------------------------------------------------
        // ProcessLangText — %s / %d substitution
        // -------------------------------------------------------

        [Fact]
        public void ProcessLangText_SubstitutesStringArg()
        {
            RunSta(() =>
            {
                var tb = Formatter.ProcessLangText("Hello %s", new object[] { "World" });
                string text = FlattenInlines(tb.Inlines);
                Assert.Contains("World", text);
            });
        }

        [Fact]
        public void ProcessLangText_SubstitutesIntArg()
        {
            RunSta(() =>
            {
                var tb = Formatter.ProcessLangText("You have %d messages", new object[] { 42 });
                string text = FlattenInlines(tb.Inlines);
                Assert.Contains("42", text);
            });
        }

        [Fact]
        public void ProcessLangText_MultipleArgs()
        {
            RunSta(() =>
            {
                var tb = Formatter.ProcessLangText("%s has %d items", new object[] { "Bag", 5 });
                string text = FlattenInlines(tb.Inlines);
                Assert.Contains("Bag", text);
                Assert.Contains("5", text);
            });
        }

        // -------------------------------------------------------
        // ProcessLangText — HTML tags
        // -------------------------------------------------------

        [Fact]
        public void ProcessLangText_BoldTag_ProducesBoldSpan()
        {
            RunSta(() =>
            {
                var tb = Formatter.ProcessLangText("<b>bold</b>", Array.Empty<object>());
                var spans = tb.Inlines.OfType<Span>();
                Assert.True(spans.Any(s => s.FontWeight == FontWeights.Bold),
                    "Expected a bold Span from <b> tag.");
            });
        }

        [Fact]
        public void ProcessLangText_AnchorTag_ProducesHyperlink()
        {
            RunSta(() =>
            {
                var tb = Formatter.ProcessLangText(
                    "<a href=\"https://skymu.app\">click</a>", Array.Empty<object>());
                Assert.True(tb.Inlines.OfType<Hyperlink>().Any(),
                    "Expected a Hyperlink from <a> tag.");
            });
        }

        [Fact]
        public void ProcessLangText_BrTag_ProducesLineBreak()
        {
            RunSta(() =>
            {
                var tb = Formatter.ProcessLangText("line1<br/>line2", Array.Empty<object>());
                Assert.True(tb.Inlines.OfType<LineBreak>().Any(),
                    "Expected a LineBreak from <br/> tag.");
            });
        }

        [Fact]
        public void ProcessLangText_FontColorTag_AppliesForeground()
        {
            RunSta(() =>
            {
                var tb = Formatter.ProcessLangText(
                    "<font color=\"#FF0000\">red</font>", Array.Empty<object>());
                var spans = tb.Inlines.OfType<Span>();
                Assert.True(spans.Any(s => s.Foreground != null),
                    "Expected a Span with a non-null Foreground from <font color>.");
            });
        }

        [Fact]
        public void ProcessLangText_NoArgs_DoesNotThrow()
        {
            RunSta(() =>
            {
                var tb = Formatter.ProcessLangText("plain text no args", Array.Empty<object>());
                Assert.NotNull(tb);
            });
        }

        [Fact]
        public void ProcessLangText_LiteralPercent_IsPreserved()
        {
            RunSta(() =>
            {
                TextBlock tb = Formatter.ProcessLangText("100%%", Array.Empty<object>());
                string text = FlattenInlines(tb.Inlines);
                Assert.True(text.Contains("%"),
                    "'%%' should produce a literal '%' character.");
            });
        }
    }
}